name: github_project_health_analytics
version: 1.0.0
config-version: 2

profile: github_project_health_analytics

model-paths: ["models"]

models:
  saas_revenue_ai_analytics:
    staging:
      +materialized: view
    marts:
      +materialized: table