name: "saas_revenue_analytics"
version: "1.0.0"
config-version: 2

profile: "saas_revenue_analytics"

model-paths: ["models"]

models:
  saas_revenue_analytics:
    staging:
      +materialized: view
    marts:
      +materialized: table