version: 2

models:

  - name: stg_repo

    columns:

      - name: repo_id

        tests:

          - not_null

          - unique

  - name: stg_issues

    columns:

      - name: issue_id

        tests:

          - not_null

          - unique

  - name: stg_pull_requests

    columns:

      - name: pr_id

        tests:

          - not_null

          - unique

  - name: stg_commits

    columns:

      - name: sha

        tests:

          - not_null

          - unique