version: 2

models:
  - name: github_project_health
    description: Repository health metrics created from GitHub API data.
    columns:
      - name: full_name
        tests:
          - not_null
      - name: stars
        description: Number of GitHub stars.
      - name: forks
        description: Number of forks.
      - name: avg_issue_resolution_days
        description: Average time to close issues in days.
      - name: avg_pr_merge_days
        description: Average time to merge pull requests in days.